/** Presentation copy only. Keep these keys out of saves and gameplay rules. */
export const LEVEL_ONE_COPY = {
  controls: '方向鍵或 A／D 移動，空白鍵跳躍。',
  resume: '紀錄還在。世界也記得自己放過多少水。',
  reverseCollected: '清點完畢 · 面值仍零',
  reverseLabel: '王庫退役幣 × 8',
  reverseDiscovery: '你特地往左找到了 8 枚王庫退役幣。守衛拒絕收兌。',
  reverseBanner: '王庫清點完成\n八枚，面值共零。',
  goalMovedLabel: '王命特許通行\n終點已主動靠近',
  ledgerTitle: '王城事故簿 · 見習者',
  ledgerStamp: '王命通過',
  firstCheckpoint: '第一道斷崖通過。王城鐘聲假裝沒緊張。',
  secondCheckpoint: '「完全安全」區已經在你後面了。',
  thirdCheckpoint: '王家木橋通過。守衛迅速把修繕槌藏回披風。',
  fallbackDeath: '這次事故仍在調查中。',
  goalMoved: '鑑於剛才的審核事故，客服把終點搬近了。這次算公開放水。',
  respawn: '再一次。已經發生的援助不會收回。',
  movingGoal: '守衛搬運中　←',
  idle: '你是在等遊戲先道歉嗎？',
  warningRevealed: '守衛翻牌：危險',
  warningRetired: '王命停用',
  safetyNet: '守衛臨時接住區',
  bridgeCertified: '王命：此橋不得再塌',
  landingStamp: '王徽',
  goalStamp: '王\n令',
  ledgerStatus: (deaths: number): string =>
    deaths === 0 ? '未記錄' : deaths >= 7 ? `× ${deaths}　王命通過` : `事故 × ${deaths}`,
  accidentPrefix: (tier: number | null): string => tier === null ? '事故' : `王城介入 ${tier}`,
} as const;
